### ISSUE TITLE
AttributeError: 'PyMISP' object has no attribute 'download_last'

### ISSUE THREAD

**Issue by azzarin** [PidgeyL/MISP-Extractor#1]
Getting error: 
Traceback (most recent call last):
  File "*/MISP-Extractor-master/bin/MISP-Extractor.py", line 53, in <module>
    data = MispEx.getMISPData(args.s)
  File "*\MISP-Extractor-master\bin\..\lib\MispExtractor.py", line 73, in getMISPData
    misp_last = misp.download_last(since)
AttributeError: 'PyMISP' object has no attribute 'download_last'

I have tried using the arg -s aswell.

**Comment by HadiElKarhani** [comment]
Hello,
I have the same issue. Has it been solved?

**Comment by sliferboy** [comment]
same here
